version: 3.0.{build}

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

install:
  - cinst cmake

clone_depth: 1

before_build:
  - echo CONFIGURATION = %CONFIGURATION%, PLATFORM = %PLATFORM%
  - mkdir _build
  - cd _build
  - set VMF_SHARED=OFF
  - if "%CONFIGURATION%"=="Debug" set VMF_SHARED=ON
  - set CMAKE_GENERATOR=Visual Studio 12 2013
  - if "%PLATFORM%"=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - echo cmake -G "%CMAKE_GENERATOR%" -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DBUILD_QT_SAMPLES=OFF -DBUILD_SHARED_LIBS=%VMF_SHARED% ..
  - cmake -G "%CMAKE_GENERATOR%" -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DBUILD_QT_SAMPLES=OFF -DBUILD_SHARED_LIBS=%VMF_SHARED% ..

build_script:
  - cmake --build . --target INSTALL --config %CONFIGURATION% -- /m /v:m

on_success:
  - dir
  - bin\%CONFIGURATION%\unit-tests.exe
  - bin\%CONFIGURATION%\unit-tests-ds.exe

test: off
