version: 3.0.{build}

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - cinst cmake

clone_depth: 1

before_build:
  - mkdir _build
  - cd _build
  - set VMF_SHARED=OFF
  - if %CONFIGURATION%=="Debug" set VMF_SHARED=ON
  - set CMAKE_GENERATOR=Visual Studio 12
  - if %PLATFORM%=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - cmake -G "Visual Studio 12 Win64" -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DBUILD_QT_SAMPLES=OFF -DBUILD_SHARED_LIBS=OFF ..
  - dir

build:
  project:   C:\projects\vmf\_build\vmf.sln
  verbosity: minimal
  parallel:  true

after_build:
  - dir
